[package]
name = "wbw-rank"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
wbw-types = { path = "../wbw-types" }
wbw-ngram = { path = "../wbw-ngram" }
serde.workspace = true
serde_json.workspace = true
lru.workspace = true
anyhow.workspace = true
thiserror.workspace = true
