[package]
name = "wbw-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "wbwime"
path = "src/main.rs"

[dependencies]
wbw-types = { path = "../wbw-types" }
wbw-dict = { path = "../wbw-dict" }
wbw-matcher = { path = "../wbw-matcher" }
wbw-rank = { path = "../wbw-rank" }
toml.workspace = true

[dev-dependencies]
wbw-core = { path = "../wbw-core" }
wbw-ngram = { path = "../wbw-ngram" }
wbw-imekit = { path = "../wbw-imekit" }
